[package]
name = "xixanta-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]
members = []

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.xixanta]
path = ".."

[[bin]]
name = "fuzz-target-parser"
path = "fuzz_targets/fuzz-target-parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz-target-assembler"
path = "fuzz_targets/fuzz-target-assembler.rs"
test = false
doc = false
bench = false
