[package]
name = "header-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]
members = []

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.header]
path = ".."

[[bin]]
name = "fuzz-target-header"
path = "fuzz_targets/fuzz-target-header.rs"
test = false
doc = false
bench = false
