[package]
name = "readrom"
version = "1.0.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "^4", features = ["derive"] }
header.workspace = true
